image: Visual Studio 2022

platform:
  - ARM64

cache:
  # Not caching node_modules because appveyor doesn't restore it afterwards (not sure why)
  # - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 20 arm64
  - yarn

build_script:
  - ps: cd ElectronClient\app
  - ./build.sh
  - npm install
  - yarn dist

test: false
