// Auto-generated by compile-package-info.js
// Do not change directly
const packageInfo = {
    "name": "@tarwitthaya/Joplin",
    "version": "0.10.26",
    "description": "Joplin for Desktop",
    "main": "main.js",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/wittaya698/joplin-clone.git"
    },
    "author": "Laurent Cozic",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/wittaya698/joplin-clone/issues"
    },
    "homepage": "https://github.com/wittaya698/joplin-clone#readme",
    "build": {
        "appId": "thongchin.witthaya.joplin-desktop"
    }
};
module.exports = packageInfo;